services:
  bot:
    image: vodogamer/watchlist-bot:latest
    env_file:
      - .env
    depends_on:
      migrations:
        condition: service_completed_successfully
    restart: unless-stopped
    volumes:
      - ./db.sqlite3:/app/db.sqlite3

  migrations:
    image: vodogamer/watchlist-bot:latest
    env_file:
      - .env
    restart: on-failure:3
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
    command: "uv run alembic upgrade head"
